version: '3'
services:
  api:
    build: .
    ports:
      - '3004:${PORT}'
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_EXPIRY: ${TOKEN_EXPIRY}
      RESET_TOKEN_EXPIRY: ${RESET_TOKEN_EXPIRY}
      PORT: ${PORT}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_MAIL: ${MAILER_MAIL}
      MAILER_PASS: ${MAILER_PASS}
      SYS_MAIL: ${SYS_MAIL}
    depends_on:
      - db
    networks:
      - nja-network

  db:
    image: postgres:15
    hostname: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
      # user
      DB_NAME:  ${DB_NAME}
      DB_USER:  ${DB_USER}
      DB_PASS:  ${DB_PASS}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    networks:
      - nja-network

networks:
  nja-network:
    driver: bridge